import { useState, type FormEvent } from 'react';
import { ArrowRight, Fingerprint, ShieldCheck } from 'lucide-react';
import { post, errorMessage } from './api';
import { Busy, Field, Notice } from './ui';
import type { User } from '../shared/types';

export function Auth({ initialized, onLogin }: { initialized: boolean; onLogin: (user: User) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [displayName, setDisplayName] = useState(''); const [token, setToken] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const result = await post<{user: User}>(initialized ? '/auth/login' : '/auth/setup', { username, password, display_name: displayName, token }); onLogin(result.user); } catch (exception) { setError(errorMessage(exception)); } finally { setBusy(false); } }
  return <main className="auth-layout"><section className="auth-story"><div className="brand"><span className="brand-symbol">C<span>↗</span></span><div>客户背调<small>Customer Background</small></div></div><div className="auth-copy"><div className="eyebrow">从线索，到有依据的客户判断</div><h1>让每一次建联，<br />都有据可依。</h1><p>将企业资料、客户线索和调研证据汇集到团队工作台，持续沉淀，可追溯、可接力。</p><div className="auth-graphic"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="graphic-node node-a">企业档案</div><div className="graphic-center"><Fingerprint size={34} /><span>精准匹配</span></div><div className="graphic-node node-b">真实证据</div><div className="graphic-node node-c">团队协作</div></div></div><div className="auth-footer"><ShieldCheck size={17} /> 仅限授权团队访问</div></section><section className="auth-form-panel"><form onSubmit={submit} className="auth-form"><span className="small-label">TEAM WORKSPACE</span><h2>{initialized ? '欢迎回到工作台' : '建立你的团队工作台'}</h2><p>{initialized ? '使用管理员分配的账号登录。' : '使用部署时设置的初始化令牌创建首个管理员。'}</p>{error && <Notice tone="error">{error}</Notice>}{!initialized && <><Field label="初始化令牌"><input type="password" autoComplete="off" value={token} onChange={event => setToken(event.target.value)} required /></Field><Field label="你的姓名"><input value={displayName} onChange={event => setDisplayName(event.target.value)} autoComplete="name" required /></Field></>}<Field label="用户名"><input value={username} onChange={event => setUsername(event.target.value)} autoComplete="username" required placeholder="输入团队账号" /></Field><Field label="密码" hint={!initialized ? '至少 12 位，建议使用密码管理器生成。' : undefined}><input type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete={initialized ? 'current-password' : 'new-password'} minLength={initialized ? undefined : 12} required placeholder="输入密码" /></Field><button className="button primary full" disabled={busy}>{busy ? <Busy /> : <>{initialized ? '登录工作台' : '创建管理员并进入'}<ArrowRight size={17} /></>}</button><div className="auth-note">不开放公开注册。账号或密码遇到问题，请联系团队管理员。</div></form></section></main>;
}

export function PasswordForm({ forced, onDone }: { forced?: boolean; onDone: () => void }) {
  const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (next !== confirm) { setError('两次输入的新密码不一致。'); return; } setBusy(true); setError(''); try { await post('/auth/password', { current_password: current, password: next }); onDone(); } catch (exception) { setError(errorMessage(exception)); } finally { setBusy(false); } }
  return <form onSubmit={submit}>{forced && <Notice>首次登录或管理员重置密码后，请先设置自己的密码。</Notice>}{error && <Notice tone="error">{error}</Notice>}<Field label="当前密码"><input type="password" autoComplete="current-password" value={current} onChange={event => setCurrent(event.target.value)} required /></Field><Field label="新密码" hint="至少 12 位。"><input type="password" autoComplete="new-password" value={next} onChange={event => setNext(event.target.value)} minLength={12} required /></Field><Field label="再次输入新密码"><input type="password" autoComplete="new-password" value={confirm} onChange={event => setConfirm(event.target.value)} minLength={12} required /></Field><button className="button primary" disabled={busy}>{busy ? <Busy /> : '保存新密码'}</button></form>;
}
